### ISSUE TITLE
manage.py migrate error

### ISSUE THREAD

**Issue by guiguiabloc** [Patrowl/PatrowlDocs#17]
Hi,
I've got an error when execute :  python manage.py migrate

django.db.utils.ProgrammingError: ERREUR:  le type  jsonb  n'existe pas
LINE 1: ...L, "criticity" varchar(10) NOT NULL, "risk_level" jsonb NOT ...

`Operations to perform:
  Apply all migrations: admin, assets, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, engines, events, findings, rules, scans, sessions, settings, users
Running migrations:
  Applying assets.0001_initial...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 319, in create_model
    self.execute(sql, params or None)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/data/PatrowlManager/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: ERREUR:  le type Â« jsonb Â» n'existe pas
LINE 1: ...L, "criticity" varchar(10) NOT NULL, "risk_level" jsonb NOT ...
                                                             ^
`

**Comment by MaKyOtOx** [comment]
Hi ! Which version of Postgresql do you use ?
According to the Django docs, JSONField requires PostgreSQL ≥ 9.4 and Psycopg2 ≥ 2.5.4

**Comment by guiguiabloc** [comment]
Arf, postgres (PostgreSQL) 9.2.24 (default package version on CentOS 7.5)
i'lll try to install a newer version :/

Thx Nicolas !

**Comment by MaKyOtOx** [comment]
Is the DB upgrade fixed your issue ?

**Comment by guiguiabloc** [comment]
yes ! sorry for not making feedback

**Comment by MaKyOtOx** [comment]
It's ok :) Thank you
