### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by omnia-projetcs** [Patrowl/PatrowlDocs#27]
Hello,
you have an issue with the Django init (python manage.py createsuperuser) and the same bug in the Docker part.

The init if the profil user is HS and you cannot logon...
last version.

**Comment by omnia-projetcs** [comment]
debug in command line install:

python manage.py createsuperuser
Username (leave blank to use 'root'): 
Email address: 
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 156, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/contrib/auth/models.py", line 162, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/contrib/auth/models.py", line 145, in _create_user
    user.save(using=self._db)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/db/models/base.py", line 788, in save_base
    post_save.send(
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/sources/PatrowlManager/users/models.py", line 57, in create_user_profile
    Profile.objects.create(user=instance, status='ACTIVE', bio="n/a", department="n/a")
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/db/models/query.py", line 420, in create
    obj = self.model(**kwargs)
  File "/sources/PatrowlManager/env3/lib/python3.8/site-packages/django/db/models/base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Profile() got an unexpected keyword argument 'bio'

**Comment by MaKyOtOx** [comment]
Hello, Thanks for your report,
This issue is fixed since https://github.com/Patrowl/PatrowlManager/tree/1.4.8
